/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/03FJFpscwzb
 */
import Link from "next/link"

export function AdithTemp() {
  return (
    (<section
      key="1"
      className="w-full py-12 bg-gradient-to-b from-green-400 to-green-600">
      <div className="container grid gap-6 md:gap-8 px-4 md:px-6 max-w-6xl mx-auto">
        <div
          className="flex flex-col md:flex-row items-start md:items-center gap-4 md:gap-8">
          <div className="grid gap-1">
            <h1 className="text-3xl font-bold tracking-tight text-white">Shop by Sport</h1>
            <p className="text-green-500 dark:text-green-400 text-white">
              Find the gear you need for your favorite sport.
            </p>
          </div>
        </div>
        <div className="grid lg:grid-cols-3 gap-8">
          <div className="grid gap-4 relative group">
            <Link className="absolute inset-0 z-10" href="#">
              <span className="sr-only">View</span>
            </Link>
            <img
              alt="Basketball"
              className="rounded-lg object-cover w-full aspect-[3/4] group-hover:opacity-50 transition-opacity"
              height={600}
              src="/placeholder.svg"
              width={450} />
            <div className="grid gap-1">
              <h3 className="font-semibold text-white">Basketball</h3>
              <p className="text-sm leading-none text-white">Styles made for your game.</p>
            </div>
            <p className="font-semibold underline underline-offset-4 text-white">Shop</p>
          </div>
          <div className="grid gap-4 relative group">
            <Link className="absolute inset-0 z-10" href="#">
              <span className="sr-only">View</span>
            </Link>
            <img
              alt="Running"
              className="rounded-lg object-cover w-full aspect-[3/4] group-hover:opacity-50 transition-opacity"
              height={600}
              src="/placeholder.svg"
              width={450} />
            <div className="grid gap-1">
              <h3 className="font-semibold text-white">Running</h3>
              <p className="text-sm leading-none text-white">Everything you need for every mile.</p>
            </div>
            <p className="font-semibold underline underline-offset-4 text-white">Shop</p>
          </div>
          <div className="grid gap-4 relative group">
            <Link className="absolute inset-0 z-10" href="#">
              <span className="sr-only">View</span>
            </Link>
            <img
              alt="Football"
              className="rounded-lg object-cover w-full aspect-[3/4] group-hover:opacity-50 transition-opacity"
              height={600}
              src="/placeholder.svg"
              width={450} />
            <div className="grid gap-1">
              <h3 className="font-semibold text-white">Football</h3>
              <p className="text-sm leading-none text-white">Command the field in game-ready gear.</p>
            </div>
            <p className="font-semibold underline underline-offset-4 text-white">Shop</p>
          </div>
        </div>
      </div>
    </section>)
  );
}
