/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Edi8ABgmnyv
 */
import { Label } from "@components/components/ui/label";
import { Input } from "@components/components/ui/input";
import { Textarea } from "@components/components/ui/textarea";
import { Button } from "@components/components/ui/button";

export function EnquiryForm() {
    return (
        <div className="w-full px-4 py-8 space-y-4 md:px-6 md:space-y-8 bg-[#D1FAE5] rounded-lg shadow-lg">
            <div className="space-y-2">
                <h2 className="text-3xl font-bold text-green-800">
                    Enquire for long stays
                </h2>
                <p className="text-gray-500 dark:text-gray-400">
                    Fill in the form and our team will get back to you with the
                    best rates.
                </p>
            </div>
            <div className="space-y-4">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="space-y-2">
                        <Label className="text-green-800" htmlFor="name">
                            Name
                        </Label>
                        <Input
                            className="bg-white text-gray-700 border border-green-300 rounded-md p-2"
                            id="name"
                            placeholder="Enter your name"
                        />
                    </div>
                    <div className="space-y-2">
                        <Label className="text-green-800" htmlFor="email">
                            Email
                        </Label>
                        <Input
                            className="bg-white text-gray-700 border border-green-300 rounded-md p-2"
                            id="email"
                            placeholder="Enter your email"
                            type="email"
                        />
                    </div>
                    <div className="space-y-2">
                        <Label className="text-green-800" htmlFor="phone">
                            Phone
                        </Label>
                        <Input
                            className="bg-white text-gray-700 border border-green-300 rounded-md p-2"
                            id="phone"
                            placeholder="Enter your phone number"
                        />
                    </div>
                    <div className="space-y-2">
                        <div className="grid grid-cols-2 gap-4">
                            <div className="space-y-2">
                                <Label
                                    className="text-green-800"
                                    htmlFor="check-in"
                                >
                                    Check-in
                                </Label>
                                <Input
                                    className="bg-white text-gray-700 border border-green-300 rounded-md p-2"
                                    id="check-in"
                                    type="date"
                                />
                            </div>
                            <div className="space-y-2">
                                <Label
                                    className="text-green-800"
                                    htmlFor="check-out"
                                >
                                    Check-out
                                </Label>
                                <Input
                                    className="bg-white text-gray-700 border border-green-300 rounded-md p-2"
                                    id="check-out"
                                    type="date"
                                />
                            </div>
                        </div>
                    </div>
                </div>
                <div className="space-y-2">
                    <Label className="text-green-800" htmlFor="message">
                        Message
                    </Label>
                    <Textarea
                        className="min-h-[100px] bg-white text-gray-700 border border-green-300 rounded-md p-2"
                        id="message"
                        placeholder="Enter your message"
                    />
                </div>
                <Button className="bg-green-500 text-white hover:bg-green-600">
                    Send enquiry
                </Button>
            </div>
        </div>
    );
}
