/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/0B9NH5Xpxtn
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'
import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import {
    CardTitle,
    CardDescription,
    CardHeader,
    CardContent,
    Card
} from "@components/components/ui/card";

export function TermsAndConditions() {
    return (
        <Card
            key="1"
            className="mt-40 w-full max-w-xl mx-auto text-gray-800 dark:text-gray-200" // Added text color classes
            style={{ backgroundColor: "aliceblue" }}
        >
            <CardHeader>
                <CardTitle className="text-gray-500 mb-1 text-xl md:text-2xl">
                    Terms & Conditions Agreement
                </CardTitle>
                <CardDescription>
                    Please read these terms and conditions carefully before
                    using our service.
                </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
                <div className="border-t border-gray-300 dark:border-gray-700 " />
                <div className="space y-4">
                    <details>
                        <summary className="flex items-center space-x-2 cursor-pointer">
                            <ChevronDownIcon className="text-gray-500 w-4 h-4" />
                            <span className="text-gray-500 font-medium text-gray-500">
                                Agreement to Terms
                            </span>
                        </summary>
                        <div className="text-gray-500 ml-6 space-y-2 text-sm text-gray-500">
                            <p>
                                These Terms and Conditions are a legally binding
                                agreement made by and between My Company and
                                you.
                            </p>
                        </div>
                    </details>
                    <details>
                        <summary className="flex items-center space-x-2 cursor-pointer">
                            <ChevronDownIcon className="text-gray-500 w-4 h-4" />
                            <span className="font-medium text-gray-500">
                                Reservations
                            </span>
                        </summary>
                        <div className="ml-6 space-y-2 text-sm text-gray-500">
                            <p>
                                The right is reserved to make changes to the
                                website and the terms and conditions at any
                                time.
                            </p>
                        </div>
                    </details>
                    <details>
                        <summary className="flex items-center space-x-2 cursor-pointer">
                            <ChevronDownIcon className="text-gray-500 w-4 h-4" />
                            <span className="font-medium text-gray-500">
                                Intellectual Property
                            </span>
                        </summary>
                        <div className="ml-6 space-y-2 text-sm text-gray-500">
                            <p>
                                The website and its original content, features,
                                and functionality are owned by My Company and
                                are protected by international copyright,
                                trademark, patent, trade secret, and other
                                intellectual property or proprietary rights
                                laws.
                            </p>
                        </div>
                    </details>
                    <details>
                        <summary className="flex items-center space-x-2 cursor-pointer">
                            <ChevronDownIcon className="text-gray-500 w-4 h-4" />
                            <span className="font-medium text-gray-500">
                                Limitation of Liability
                            </span>
                        </summary>
                        <div className="ml-6 space-y-2 text-sm text-gray-500">
                            <p>
                                In no event shall My Company, nor its directors,
                                employees, partners, agents, suppliers, or
                                affiliates, be liable for any indirect,
                                incidental, special, consequential, or punitive
                                damages, including without limitation, loss of
                                profits, data, use, goodwill, or other
                                intangible losses, resulting from (i) your
                                access to or use of or inability to access or
                                use the Service; (ii) any conduct or content of
                                any third party on the Service; (iii) any
                                content obtained from the Service; and (iv)
                                unauthorized access, use or alteration of your
                                transmissions or content, whether based on
                                warranty, contract, tort (including negligence)
                                or any other legal theory, whether or not we
                                have been informed of the possibility of such
                                damage, and even if a remedy set forth herein is
                                found to have failed of its essential purpose.
                            </p>
                        </div>
                    </details>
                    <details>
                        <summary className="flex items-center space-x-2 cursor-pointer">
                            <ChevronDownIcon className="text-gray-500 w-4 h-4" />
                            <span className="font-medium text-gray-500">
                                Updates
                            </span>
                        </summary>
                        <div className="ml-6 space-y-2 text-sm text-gray-500">
                            <p />
                        </div>
                    </details>
                </div>
            </CardContent>
        </Card>
    );
}

function ChevronDownIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="m6 9 6 6 6-6" />
        </svg>
    );
}
